### ISSUE TITLE
Link para o artigo

### ISSUE THREAD

**Issue by jfsiebel** [leonardopaula/ping-pong#1]
Qual o link para o artigo? Procurei nos meu emails e não encontrei, hoje a noite vou montar uma estrutura para a apresentação.

**Comment by GustavoSchroeder** [comment]
Cara, me passa teu contato de whatsapp, aqui fica complicado trabalhar, precisamos discutir várias coisas... Se tu puder por favor me passa.

**Comment by GustavoSchroeder** [comment]
guto_schroeder@hotmail.com
